{% set version = "3.0.0" %}

package:
  name: smmap2
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/smmap2/smmap2-{{ version }}.tar.gz
  sha256: 503ee18c47935b88ed728d8fd59dadfe04b0f80dbc7e325c1fda6cf2f01c36b2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - smmap

about:
  home: https://github.com/gitpython-developers/smmap
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'A pure python implementation of a sliding window memory map manager'

extra:
  recipe-maintainers:
    - ocefpaf
